name: chat_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  firebase_analytics: ^10.8.9
  file_picker: ^8.0.0+1
  timeago: ^3.6.1
  flutter_spinkit: ^5.2.0
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_auth: ^4.17.8
  get_it: ^7.6.7
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
